version: '3.8'

services:
  app:
    image: node:16
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - '3000:3000'
    environment:
      - UV_THREADPOOL_SIZE=1
    stdin_open: true
    tty: true
    entrypoint: |
      sh -c "
      rm -rf node_modules &&
      npm install --legacy-peer-deps &&
      npm run build-prod &&
      npm run start
      "
